# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_foodtype_mianshow_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mianshow',
            old_name='logname1',
            new_name='longname1',
        ),
        migrations.RenameField(
            model_name='mianshow',
            old_name='logname2',
            new_name='longname2',
        ),
        migrations.RenameField(
            model_name='mianshow',
            old_name='logname3',
            new_name='longname3',
        ),
    ]
