# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181213_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table='axf_foodtypes',
        ),
    ]
