# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-16 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20181213_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MianShow',
            new_name='MainShow',
        ),
    ]
